// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.gclopes.ProtoBuffServerAPP.Proto;

public interface messageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:gclopes.message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required string msgToSend = 1;</code>
   * @return Whether the msgToSend field is set.
   */
  boolean hasMsgToSend();
  /**
   * <code>required string msgToSend = 1;</code>
   * @return The msgToSend.
   */
  java.lang.String getMsgToSend();
  /**
   * <code>required string msgToSend = 1;</code>
   * @return The bytes for msgToSend.
   */
  com.google.protobuf.ByteString
      getMsgToSendBytes();
}
