// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

package com.gclopes.ProtoBuffServerAPP.Proto;

/**
 * Protobuf type {@code gclopes.message}
 */
public final class message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:gclopes.message)
    messageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use message.newBuilder() to construct.
  private message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private message() {
    msgToSend_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000001;
            msgToSend_ = bs;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.gclopes.ProtoBuffServerAPP.Proto.MessageProtoClass.internal_static_gclopes_message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.gclopes.ProtoBuffServerAPP.Proto.MessageProtoClass.internal_static_gclopes_message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.gclopes.ProtoBuffServerAPP.Proto.message.class, com.gclopes.ProtoBuffServerAPP.Proto.message.Builder.class);
  }

  private int bitField0_;
  public static final int MSGTOSEND_FIELD_NUMBER = 1;
  private volatile java.lang.Object msgToSend_;
  /**
   * <code>required string msgToSend = 1;</code>
   * @return Whether the msgToSend field is set.
   */
  @java.lang.Override
  public boolean hasMsgToSend() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required string msgToSend = 1;</code>
   * @return The msgToSend.
   */
  @java.lang.Override
  public java.lang.String getMsgToSend() {
    java.lang.Object ref = msgToSend_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        msgToSend_ = s;
      }
      return s;
    }
  }
  /**
   * <code>required string msgToSend = 1;</code>
   * @return The bytes for msgToSend.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMsgToSendBytes() {
    java.lang.Object ref = msgToSend_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      msgToSend_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasMsgToSend()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, msgToSend_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, msgToSend_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.gclopes.ProtoBuffServerAPP.Proto.message)) {
      return super.equals(obj);
    }
    com.gclopes.ProtoBuffServerAPP.Proto.message other = (com.gclopes.ProtoBuffServerAPP.Proto.message) obj;

    if (hasMsgToSend() != other.hasMsgToSend()) return false;
    if (hasMsgToSend()) {
      if (!getMsgToSend()
          .equals(other.getMsgToSend())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasMsgToSend()) {
      hash = (37 * hash) + MSGTOSEND_FIELD_NUMBER;
      hash = (53 * hash) + getMsgToSend().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.gclopes.ProtoBuffServerAPP.Proto.message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.gclopes.ProtoBuffServerAPP.Proto.message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code gclopes.message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:gclopes.message)
      com.gclopes.ProtoBuffServerAPP.Proto.messageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.gclopes.ProtoBuffServerAPP.Proto.MessageProtoClass.internal_static_gclopes_message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.gclopes.ProtoBuffServerAPP.Proto.MessageProtoClass.internal_static_gclopes_message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.gclopes.ProtoBuffServerAPP.Proto.message.class, com.gclopes.ProtoBuffServerAPP.Proto.message.Builder.class);
    }

    // Construct using com.gclopes.ProtoBuffServerAPP.Proto.message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      msgToSend_ = "";
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.gclopes.ProtoBuffServerAPP.Proto.MessageProtoClass.internal_static_gclopes_message_descriptor;
    }

    @java.lang.Override
    public com.gclopes.ProtoBuffServerAPP.Proto.message getDefaultInstanceForType() {
      return com.gclopes.ProtoBuffServerAPP.Proto.message.getDefaultInstance();
    }

    @java.lang.Override
    public com.gclopes.ProtoBuffServerAPP.Proto.message build() {
      com.gclopes.ProtoBuffServerAPP.Proto.message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.gclopes.ProtoBuffServerAPP.Proto.message buildPartial() {
      com.gclopes.ProtoBuffServerAPP.Proto.message result = new com.gclopes.ProtoBuffServerAPP.Proto.message(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        to_bitField0_ |= 0x00000001;
      }
      result.msgToSend_ = msgToSend_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.gclopes.ProtoBuffServerAPP.Proto.message) {
        return mergeFrom((com.gclopes.ProtoBuffServerAPP.Proto.message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.gclopes.ProtoBuffServerAPP.Proto.message other) {
      if (other == com.gclopes.ProtoBuffServerAPP.Proto.message.getDefaultInstance()) return this;
      if (other.hasMsgToSend()) {
        bitField0_ |= 0x00000001;
        msgToSend_ = other.msgToSend_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasMsgToSend()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.gclopes.ProtoBuffServerAPP.Proto.message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.gclopes.ProtoBuffServerAPP.Proto.message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object msgToSend_ = "";
    /**
     * <code>required string msgToSend = 1;</code>
     * @return Whether the msgToSend field is set.
     */
    public boolean hasMsgToSend() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string msgToSend = 1;</code>
     * @return The msgToSend.
     */
    public java.lang.String getMsgToSend() {
      java.lang.Object ref = msgToSend_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          msgToSend_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>required string msgToSend = 1;</code>
     * @return The bytes for msgToSend.
     */
    public com.google.protobuf.ByteString
        getMsgToSendBytes() {
      java.lang.Object ref = msgToSend_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        msgToSend_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>required string msgToSend = 1;</code>
     * @param value The msgToSend to set.
     * @return This builder for chaining.
     */
    public Builder setMsgToSend(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msgToSend_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required string msgToSend = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMsgToSend() {
      bitField0_ = (bitField0_ & ~0x00000001);
      msgToSend_ = getDefaultInstance().getMsgToSend();
      onChanged();
      return this;
    }
    /**
     * <code>required string msgToSend = 1;</code>
     * @param value The bytes for msgToSend to set.
     * @return This builder for chaining.
     */
    public Builder setMsgToSendBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      msgToSend_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:gclopes.message)
  }

  // @@protoc_insertion_point(class_scope:gclopes.message)
  private static final com.gclopes.ProtoBuffServerAPP.Proto.message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.gclopes.ProtoBuffServerAPP.Proto.message();
  }

  public static com.gclopes.ProtoBuffServerAPP.Proto.message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<message>
      PARSER = new com.google.protobuf.AbstractParser<message>() {
    @java.lang.Override
    public message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.gclopes.ProtoBuffServerAPP.Proto.message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

